### ISSUE TITLE
Blog TODO

### ISSUE THREAD

**Issue by RG9** [RG9/rg9.github.io#2]
- [x] setup comments - https://giscus.app/ looks appealing bc of reactions
- [x] setup analytics - https://www.goatcounter.com looks legit - free and non tracking 
- [x] why comments don't work - changed to https://github.com/apps/utterances bc looks simpler
- [x] why goatcounter respond with CORS error?  - I had to enabled "Allow adding visitor counts on your website" in settings
- [ ] automate adding posts
- [ ] automate sharing posts
